name: Extract System Notifications and Update Notion

on:
  push:
    branches: [main]
    paths:
      - 'src/assets/i18n/en.json'
  pull_request:
    branches: [main]
    paths:
      - 'src/assets/i18n/en.json'

jobs:
  extract-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq python3-pip

      - name: Run CSV extraction script
        run: bash scripts/extract-system-notifications.sh

      - name: Install Python dependencies
        run: pip install pandas requests

      - name: Update Notion table from CSV
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python .github/scripts/update_notion_table.py
