name: Extract System Notifications and Update Notion

on:
  push:
    branches: [main]
    paths:
      - 'src/assets/i18n/en.json'
  pull_request:
    branches: [main]
    paths:
      - 'src/assets/i18n/en.json'

jobs:
  extract-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install pandas requests

      - name: Extract system notifications to CSV
        run: python scripts/extract-system-notifications.py

      - name: Update Notion tables from CSVs
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_NOTIF_DB_ID: ${{ secrets.NOTION_NOTIF_DB_ID }}
          NOTION_PARAMS_DB_ID: ${{ secrets.NOTION_PARAMS_DB_ID }}
        run: python scripts/update_notion_table.py
